config/routes.rb
Rails.application.routes.draw do

  resources :videos, only: [:index, :new, :create, :edit, :update, :destroy]
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :videos
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  validates :name, :url, presence: true

  validate :video_format
 
  def video_format
    if url.present? && !url.to_s.end_with?(".m3u8")
      errors.add(:url, I18n.t("errors.messages.not_equal_to_format"))
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = current_user.videos.build(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to videos_url, notice: I18n.t('form.success') }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to videos_url, notice: I18n.t('form.success') }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: I18n.t('form.success') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      begin
        @video = current_user.videos.find(params[:id])
      rescue => exception
        redirect_to videos_url, notice: I18n.t('errors.without_permission')
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:name, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def resource_name
  #   :user
  # end

  # def resource
  #   @resource ||= User.new
  # end

  # def devise_mapping
  #   @devise_mapping ||= Devise.mappings[:user]
  # end
end

app/helpers/devise_helper.rb
# frozen_string_literal: true

module DeviseHelper
  # Retain this method for backwards compatibility, deprecated in favour of modifying the
  # devise/shared/error_messages partial
  def devise_error_messages!
    return "" if resource.errors.empty?

    render "devise/shared/error_messages", resource: resource
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/home/index.html.haml
%section.section
  .columns.is-mobile.is-centered
    .column.is-half
      .card
        %header.card-header
          %h3.title.is-3.card-header-title.is-centered
            = t('home.title')
        .card-content
          .content
            %p.subtitle
              = t('home.description', videos_count: Video.count)
        %footer.card-footer
          = link_to t('header_links.new_video'), new_video_url, class: 'card-footer-item'

app/views/layouts/_footer.html.haml
%footer.hero-footer
  .columns.is-centered
    .column.is-half
      %nav.tabs
        .container
          %ul
            %li
              = link_to t('footer_links.advertising'), '#'
            %li
              = link_to t('footer_links.business'), '#'
            %li
              = link_to t('footer_links.about_is'), '#'
    .column.is-half
      %nav.tabs
        .container
          %ul
            %li
              = link_to t('footer_links.privacy'), '#'
            %li
              = link_to t('footer_links.terms'), '#'
            %li
              = link_to t('footer_links.definitions'), '#'

app/views/layouts/_header.html.haml
%section.hero.is-warning.is-primary.is-primary-with-navbar
  .hero-body
    .container
      %h1.title.is-1
        %i.fa.fa-video
        #{t(:application_name)}
      - if user_signed_in?
        %h3.subtitle.is-4
          #{t(:application_description)}

app/views/layouts/_menu.html.haml
%nav.navbar.is-warning.is-fixed-top
  .navbar-brand
    .navbar-burger.burger{"data-target" => "navbar-transparent"}
      %span
      %span
      %span
  #navbar-transparent.navbar-menu
    .navbar-end
      - if user_signed_in?
        = link_to t('header_links.new_video'), new_video_path, class: 'navbar-item'
        = link_to t('header_links.videos'), videos_path, class: 'navbar-item'
        = link_to t('header_links.edit_user_registration'), edit_user_registration_path, class: 'navbar-item'
        = link_to t('header_links.destroy_user_session'), destroy_user_session_path, method: :delete, class: 'navbar-item'
      - else
        = link_to t('header_links.new_user_session'), new_user_session_path, class: 'navbar-item'
        = link_to t('header_links.new_user_registration'), new_user_registration_path, class: 'navbar-item'

app/views/layouts/_notifications.html.haml
- unless flash.blank?
  .notification.notification-absolute
    %button.delete
    - flash.each do |key, value|
      = value

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{charset: "UTF-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %meta{content: "ie=edge", "http-equiv" => "X-UA-Compatible"}/
    %title= t('application_name')
    %link{crossorigin: "anonymous", href: "https://use.fontawesome.com/releases/v5.6.1/css/all.css", integrity: "sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP", rel: "stylesheet"}/

    %meta{content: "#{t('application_description')}", name: "description"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.site
    = render partial: 'layouts/menu'
    = render partial: 'layouts/notifications'
    %main
      = render partial: 'layouts/header'
      = yield
    = render partial: 'layouts/footer'
      

app/views/videos/_form.html.haml
%section.section
  .section-heading
    %h3.title.is-3 #{t('videos.form.title')}
    %h4.subtitle.is-5 #{t('videos.form.subtitle', videos_count: 1)}
  .container.has-text-centered
    .columns.is-mobile.is-centered
      .column.is-half
        .card
          .card-content
            .content
              = form_for @video do |f|
                - if @video.errors.any?
                  %ul
                    - @video.errors.full_messages.each do |message|
                      %li= message
                .field
                  = f.text_field :name, class: 'input', placeholder: Video.human_attribute_name(:name)
                .field
                  = f.text_field :url, class: 'input', placeholder: Video.human_attribute_name(:url)
                - if !@video.new_record? && !@video.url.blank?
                  .is-centered
                    %video#example-video.video-js.vjs-default-skin{controls: "", width: 300}
                      %source{src: "#{@video.url}", type: "application/x-mpegURL"}
                  :javascript
                    var player = videojs('example-video');
                .actions
                  = f.submit t('form.save'), class: 'button is-fullwidth is-link'
          %footer.card-footer
            = link_to t('form.back_to_list'), videos_path, class: 'card-footer-item'

app/views/videos/_video.html.haml
%tr{title: "#{video.name}"}
  %td= truncate(video.name, length: 15)
  %td #{truncate(video.url)}
  %td #{l(video.created_at, format: :short)}
  %td #{l(video.updated_at, format: :short)}
  %td
    .buttons.has-addons
      = link_to t('admin.actions.edit.menu'), edit_video_path(video), class: 'button is-small is-info'
      = link_to t('admin.actions.delete.menu'), video, method: :delete, class: 'button is-small is-danger'

app/views/videos/edit.html.haml
= render 'form'

app/views/videos/index.html.haml
%section.section
  .section-heading
    %h3.title.is-3 #{t('videos.index.title')}
    %h4.subtitle.is-5 #{t('videos.index.subtitle', videos_count: current_user.videos.count)}
  .container.has-text-centered
    %table.table.is-striped.is-hoverable.is-fullwidth
      %thead
        %tr
          %th
            %abbr{title: Video.human_attribute_name(:name)} #{Video.human_attribute_name(:name)}
          %th
            %abbr{title: Video.human_attribute_name(:url)} #{Video.human_attribute_name(:url)}
          %th
            %abbr{title: Video.human_attribute_name(:created_at)} #{Video.human_attribute_name(:created_at)}
          %th
            %abbr{title: Video.human_attribute_name(:updated_at)} #{Video.human_attribute_name(:updated_at)}
      %tbody
        - current_user.videos.each do |video|
          = render 'video', video: video

app/views/videos/new.html.haml
= render 'form'